// <auto-generated />
using System;
using AspNetCoreBank.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AspNetCoreBank.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190807201950_Clients")]
    partial class Clients
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085");

            modelBuilder.Entity("AspNetCoreBank.Models.ClientRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<int>("Document");

                    b.Property<string>("Lastname")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new { Id = new Guid("7a42605e-f063-4318-a2dd-6676a8838bcf"), Date = new DateTime(2019, 8, 7, 17, 19, 50, 799, DateTimeKind.Local), Document = 95699120, Lastname = "Umanchuk", Name = "Jury" },
                        new { Id = new Guid("78461615-92f6-497d-aa2c-c296b24b6978"), Date = new DateTime(2019, 8, 7, 17, 19, 50, 799, DateTimeKind.Local), Document = 95885263, Lastname = "Perez", Name = "Linda" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
