// <auto-generated />
using System;
using AspNetCoreBank.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AspNetCoreBank.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190811175530_CoreBank")]
    partial class CoreBank
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("AspNetCoreBank.Models.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<int>("Document");

                    b.Property<string>("Lastname")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = new Guid("025254af-24fa-4566-b67d-0b0e29e906a5"),
                            Date = new DateTime(2019, 8, 11, 14, 55, 29, 959, DateTimeKind.Local).AddTicks(8560),
                            Document = 95699120,
                            Lastname = "Umanchuk",
                            Name = "Jury"
                        },
                        new
                        {
                            Id = new Guid("986ec1ef-3e95-4871-b397-30cccdac6c88"),
                            Date = new DateTime(2019, 8, 11, 14, 55, 29, 960, DateTimeKind.Local).AddTicks(6186),
                            Document = 95885263,
                            Lastname = "Perez",
                            Name = "Linda"
                        });
                });

            modelBuilder.Entity("AspNetCoreBank.Models.ProductType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Product_type");

                    b.Property<string>("name");

                    b.Property<int>("status");

                    b.HasKey("Id");

                    b.ToTable("ProductType");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5fdf6ab0-2727-4d4e-87dc-50843c3827da"),
                            Product_type = 1,
                            name = "Cuenta Ahorro",
                            status = 1
                        },
                        new
                        {
                            Id = new Guid("69fef123-bd64-45cb-a6c5-8995d849c8ac"),
                            Product_type = 1,
                            name = "Cuenta Corriente",
                            status = 2
                        },
                        new
                        {
                            Id = new Guid("14fc858f-cb50-46ec-9dfd-5eccf18af068"),
                            Product_type = 2,
                            name = "Prestamo Personal",
                            status = 3
                        });
                });

            modelBuilder.Entity("AspNetCoreBank.Models.Products", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("Closing_date");

                    b.Property<int>("Document");

                    b.Property<DateTime>("Opening_date");

                    b.Property<long>("Product_id");

                    b.Property<int>("Product_type");

                    b.Property<decimal>("current_balance");

                    b.Property<decimal>("status");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c44b5b8e-6272-4f42-b1ce-e1dba25e1f33"),
                            Document = 95699120,
                            Opening_date = new DateTime(2019, 8, 11, 14, 55, 29, 961, DateTimeKind.Local).AddTicks(9790),
                            Product_id = 7534563210L,
                            Product_type = 1,
                            current_balance = 0m,
                            status = 1m
                        },
                        new
                        {
                            Id = new Guid("077a0b92-9c7d-4aec-a4c8-5c3aebcbf650"),
                            Document = 95699120,
                            Opening_date = new DateTime(2019, 8, 11, 14, 55, 29, 962, DateTimeKind.Local).AddTicks(339),
                            Product_id = 7547854268L,
                            Product_type = 2,
                            current_balance = 0m,
                            status = 1m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
