// <auto-generated />
using System;
using AspNetCoreBank.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AspNetCoreBank.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190806180848_AddClients")]
    partial class AddClients
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085");

            modelBuilder.Entity("AspNetCoreBank.Models.ClientRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<string>("Lastname")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new { Id = new Guid("32ec5934-0864-4615-a9bc-4a95e437c8ea"), Date = new DateTime(2019, 8, 6, 15, 8, 48, 732, DateTimeKind.Local), Lastname = "Umanchuk", Name = "Jury" },
                        new { Id = new Guid("993d74a1-4445-46b4-885c-47f427bf99d5"), Date = new DateTime(2019, 8, 6, 15, 8, 48, 732, DateTimeKind.Local), Lastname = "Perez", Name = "Linda" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
